### ISSUE TITLE
Fix wrong answer

### ISSUE THREAD

**Issue by invzhi** [SimonZoo/Algorithm#1]
https://github.com/SimonZoo/Algorithm/blob/8221f03ebbf5a17e9c6a4954469421dd0e24a901/PAT/1009.c#L11

If `i == 0`, then `j == 0`, code this line will access `b_word[-1]`.

Add `if (j > 0)` can fix it.

**Comment by SimonZoo** [comment]
Thx ! I have modified it.XD
