### ISSUE TITLE
Please initialize your char array

### ISSUE THREAD

**Issue by invzhi** [SimonZoo/Algorithm#3]
https://github.com/SimonZoo/Algorithm/blob/3df7d932dbceaf6b73e395be7340e3b10d937127/PAT/Advanced/1035.c#L20
Before you do this, you can not assume `modify[count]` is a empty string like `""`.
Therefore, you should initialize it: `modify[count][0] = '\0';`

**Comment by SimonZoo** [comment]
Thanks!
